version: '3.9'

services:
  facade:
    image: "traefik:v2.10"
    container_name: facade-tra
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./facade/traefik/tls.yml:/etc/traefik/tls.yml"
      - "./certs/traefik:/etc/ssl/traefik"


  front:
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: front-sve
    ports: 
      - "8081:8080"

    volumes: 
      - ./front:/app
      
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.front.entrypoints=http"
      - "traefik.http.routers.front.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.front.priority=1"
      
      - "traefik.http.routers.front-ssl.entrypoints=https"
      - "traefik.http.routers.front-ssl.tls=true"
      - "traefik.http.routers.front-ssl.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.front-ssl.priority=1"

  static_media:
    image: nginx:alpine3.18
    container_name: static-media-ng

    environment:
      - NGINX_PORT=8080

    ports:
      - "8082:8080"

    volumes:

      - ./static_media/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./static_media/nginx/etc/conf.d:/etc/nginx/conf.d
      - ./static_media/nginx/entrypoint.d:/docker-entrypoint.d
      - ./static_media/nginx/cache:/var/www_cache
      - ./static_media/media:/var/www

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip_media.stripprefix.prefixes=/media,/media/" 
      - "traefik.http.services.static_media.loadbalancer.server.port=8080"

      - "traefik.http.routers.static_media.entrypoints=http" 
      - "traefik.http.routers.static_media.rule=HostRegexp(`{host:.+}`) && (Path(`/media`) || PathPrefix(`/media/`))" 
      - "traefik.http.routers.static_media.priority=100" 
      - "traefik.http.routers.static_media.middlewares=strip_media@docker"

      - "traefik.http.routers.static_media-ssl.entrypoints=https" 
      - "traefik.http.routers.static_media-ssl.tls=true"
      - "traefik.http.routers.static_media-ssl.rule=HostRegexp(`{host:.+}`) && (Path(`/media`) || PathPrefix(`/media/`))" 
      - "traefik.http.routers.static_media-ssl.priority=100" 
      - "traefik.http.routers.static_media-ssl.middlewares=strip_media@docker"

  back:
    image: "wiremock/wiremock:3.3.1-1"
    container_name: back-mock
    volumes:
      - ./back/wiremock:/home/wiremock

    ports:
      - "8083:8080"

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip_api.stripprefix.prefixes=/api,/api/" 

      - "traefik.http.routers.back.entrypoints=http" 
      - "traefik.http.routers.back.rule=HostRegexp(`{host:.+}`) && (Path(`/api`) || PathPrefix(`/api/`))" 
      - "traefik.http.routers.back.priority=50" 
      - "traefik.http.routers.back.middlewares=strip_api@docker"

      - "traefik.http.routers.back-ssl.entrypoints=https" 
      - "traefik.http.routers.back-ssl.tls=true" 
      - "traefik.http.routers.back-ssl.rule=HostRegexp(`{host:.+}`) && (Path(`/api`) || PathPrefix(`/api/`))" 
      - "traefik.http.routers.back-ssl.priority=50" 
      - "traefik.http.routers.back-ssl.middlewares=strip_api@docker"


    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]