# ### build stage #1
# FROM node:20.10.0-alpine3.18 as build_1
# WORKDIR /app
# COPY . .
# RUN npm install

# ### build stage #2
# FROM node:20.10.0-alpine3.18 as build_2

# WORKDIR /app
# COPY --from=build_1 /app .
# RUN npm ci
# RUN npm run build
# CMD ["npm", "run", "dev", "--", "--host", "--port", "8080"]


# ### run stage
# FROM node:20.10.0-alpine3.18

# WORKDIR /app
# COPY --from=build_2 /app .
# COPY . .

# EXPOSE 3000
# # CMD ["node", "./build"]
# CMD ["npm", "run", "dev"]